### ISSUE TITLE
File not found: /favicon.ico

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-rest-client-reactjs#19]
When hit the url http://gilberts-mbp.lan:9080, got following warning:

`[INFO] [WARNING ] SRVE0190E: File not found: /favicon.ico`

**Comment by DannyS03** [comment]
- looks like the browser expectation not being met, investigating.

**Comment by gkwan-ibm** [comment]
2 opinions:
1. Remove the requirement of the favicon.ico from the app
2. add the favicon.ico to the app. It is available at https://github.com/OpenLiberty/sample-getting-started/tree/master/src/main/webapp/img

**Comment by gkwan-ibm** [comment]
close
- the issue was fixed by adding the favicon.ico file to the application
